config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :user_profiles, except: [:show]

  get 'user_profiles/list'
  get '/user_profiles/:id', to: 'user_profiles#index', as: 'user_view'

  root 'user_profiles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true
  validates :age, presence: true
  validates :phone_number,:presence => true,
            :numericality => true,
            :length => { :minimum => 10, :maximum => 10 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :age, :phone_number])
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, only: [:edit, :list, :destroy]
  skip_before_action :verify_authenticity_token
  def index
    if params[:id]
      if current_user.role == 'admin'
        @user = User.find(params[:id])
      else
        redirect_to root_path
      end
    else
      @user = current_user
    end
  end

  def new
    @users = User.new
  end

  def edit

    @users = User.find(params[:id])

  end

  def list
      @users = User.where(role: nil)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to :back
  end

  def create
    @users = User.new(params_user)
    if @users.save
      redirect_to user_profiles_list_path
    else
      render 'new'
    end
  end

  def update
    @users = User.find(params[:id])
    if @users.update_attributes(params_user)
      redirect_to user_profiles_list_path
    else
    render 'edit'
    end
  end

  def authenticate_admin!
    unless current_user.role == 'admin'
      redirect_to root_path
    end
  end


  private

  def params_user
    params_user = params.require(:user).permit(:email, :password, :password_confirmation, :username, :phone_number, :age)
    params_user.delete(:password) unless params_user[:password].present?
    params_user.delete(:password_confirmation) unless params_user[:password_confirmation].present?
    params_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
    <ul class="nav">
      <% if user_signed_in? %>
          <% if current_user.role == 'admin' %>
              <li><%= link_to 'Manage User', user_profiles_list_path %></li>
              <li><%= link_to 'Add New User',new_user_profile_path %></li>
                <li><%= link_to 'Edit ME',edit_user_profile_path(current_user.id)%></li>
          <%end%>
      <%end%>
      <li><%= link_to "Logout", destroy_user_session_path, :method => :delete%></li>
      <%= render 'layouts/navigation_links' %>
    </ul>
<%end%>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Project" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Project" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="navigation">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
  </div>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
      <ul>
        <% target.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/user_profiles/edit.html.erb
<div class="benefits">
  <div class="container">
    <!--<div class="title">Benefits</div>-->
    <div class="title" style="color: darkblue">Add User</div>
    <%= form_for(@users, url: user_profile_path) do |f| %>
        <%= render partial: 'shared/error_messages', locals: {:target => @users} %>

        <div class= "field" style="margin-bottom: 10px;">
          <%= f.label :username %><br />
          <%= f.text_field :username, autofocus:true %>
        </div>

        <div class="field" style="margin-bottom: 10px;">
          <%= f.label :email %><br />
          <%= f.email_field :email%>
        </div>

        <div class="field" style="margin-bottom: 10px;">
          <%= f.label :password %>
          <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off" %>
        </div>


        <div class="field" style="margin-bottom: 10px;">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off" %>
        </div>

        <div class="field" style="margin-bottom: 10px;">
          <%= f.label :age %><br />
          <%= f.text_field :age, autocomplete: "off" %>
        </div>

        <div class="field" style="margin-bottom: 10px;">
          <%= f.label :phone_number %><br />
          <%= f.text_field :phone_number, autocomplete: "off" %>
        </div>

        <div style="margin-top: 30px; margin-left: 60px;">
          <%= button_to "Submit" %>
        </div>

    <% end %>
  </div>
</div>

app/views/user_profiles/index.html.erb
<div class="index">
  <div class="title">Profile</div>


  <div class="view-profile">
    <h1>

      <%= image_tag @user.gravatar_url %>
      <%= @user.username %>
      <ul>
        <h6 style="color: darkblue">

          <dd> Email - <%=@user.email%> </dd>
          <dd> Age - <%=@user.age%></dd>
          <dd> Phone Number - <%=@user.phone_number%></dd>
        </h6>
      </ul>
    </h1>
  </div>
</div>

app/views/user_profiles/list.html.erb
<div class="index">
  <div class="title">Users List</div>
  <div class="list">
    <% @users.each do |list|%>
        <ul>
          <%= image_tag list.gravatar_url %>
          <div class="usr-list">
            <%= link_to list.username, user_view_path(list.id)%>
            <%= link_to 'Edit', edit_user_profile_path(list.id)%>
            <%=link_to 'Delete', user_profile_path(list), :data => {:confirm => 'Are you sure?'}, :method => :delete %>
          </div>
        </ul>
    <% end %>
  </div>
</div>

app/views/user_profiles/new.html.erb
<div class="benefits">
  <div class="container">
    <!--<div class="title">Benefits</div>-->
    <div class="title" style="color: darkblue">Add User</div>
    <%= form_for(@users, url: user_profiles_path) do |f| %>
        <%= render :partial => 'shared/error_messages', locals: {:target => @users} %>

        <div class= "field" style="margin-bottom: 10px;">
          <%= f.label :username %><br />
          <%= f.text_field :username, autofocus:true %>
        </div>

        <div class="field" style="margin-bottom: 10px;">
          <%= f.label :email %><br />
          <%= f.email_field :email%>
        </div>

        <div class="field" style="margin-bottom: 10px;">
          <%= f.label :password %>
          <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off" %>
        </div>


        <div class="field" style="margin-bottom: 10px;">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off" %>
        </div>

        <div class="field" style="margin-bottom: 10px;">
          <%= f.label :age %><br />
          <%= f.text_field :age, autocomplete: "off" %>
        </div>

        <div class="field" style="margin-bottom: 10px;">
          <%= f.label :phone_number %><br />
          <%= f.text_field :phone_number, autocomplete: "off" %>
        </div>

        <div style="margin-top: 30px; margin-left: 60px;">
          <%= button_to "Submit" %>
        </div>

    <% end %>
  </div>
</div>